let dados = [
    { 
        titulo : "Acidente Vascular Cerebral",
        descricao : "O AVC é uma doença que ocorre quando o suprimento de sangue para uma área do cérebro é interrompido ou quando um vaso sanguíneo no cérebro se rompe. Isso causa a morte das células cerebrais e pode levar a incapacidade permanente ou morte.",
        nivel_de_emergencia : "Emergência Crítica",
        casos_por_ano : "Aproximadamente 150 Mil Casos",
        link_para_ligacao : "tel:+55192",
        nos_musculos : "fraqueza, paralisia, dificuldade para andar, perda de coordenação.",
        na_visao : "visão dupla, embaçada, perda de visão em um olho.",
        na_fala : "dificuldade para falar, fala arrastada ou incompreensível.",
        no_corpo : "tontura, dor de cabeça intensa, perda de equilíbrio.",
        sensorial : "formigamento ou dormência em um lado do corpo.",
        na_cognicao : "confusão mental, dificuldade para entender ou falar.",
        no_rosto : "fraqueza ou paralisia em um lado do rosto.",
        intensidade : "Variável - Pode ser leve, moderada ou grave, dependendo da área do cérebro afetada.",
        duração : "Variável - Os sintomas podem ser súbitos e durar minutos ou horas, ou podem ser progressivos e durar dias.",
        causas : "Obstrução ou Ruptura de um vaso sanguíneo no cérebro",
        fatores_de_risco : "Idade, hipertensão, diabetes, colesterol alto, tabagismo, sedentarismo, fibrilação atrial, doenças cardíacas, histórico familiar de AVC.",
        fatores_agravantes : "Hipertensão arterial, diabetes, colesterol alto, tabagismo, sedentarismo, idade avançada, doenças cardíacas.",
        fatores_aliviantes : "Não há fatores que aliviem os sintomas de um AVC de forma imediata.",
        prevencao : "Controle da pressão arterial, diabetes e colesterol, prática de atividade física regular, alimentação saudável, abandono do tabagismo.",
        tratamento : "O tratamento depende do tipo de AVC e da sua gravidade. Geralmente envolve medicamentos para dissolver coágulos, cirurgia ou reabilitação.",
        link_artigo : "http://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/a/avc",
        link_video : "https://www.youtube.com/watch?v=fMrJygd-gmw&pp=ygUDYXZj",
    },

    {
        titulo : "Infarto Agudo do Miocárdio",
        descricao : "O infarto agudo do miocárdio, também conhecido como ataque cardíaco, ocorre quando o fluxo de sangue para uma parte do coração é bloqueado por um longo período de tempo, causando danos ou morte do músculo cardíaco.",
        nivel_de_emergencia : "Emergência Crítica",
        casos_por_ano : "Cerca de 150 Mil Casos",
        link_para_ligacao : "tel:+55192",
        nos_musculos : "dor no peito que pode irradiar para o braço, ombro, costas ou mandíbula.",
        na_visao : "visão turva ou escurecida pode ocorrer, mas não é um sintoma comum.",
        na_fala : "pode haver dificuldade para falar devido à dor ou falta de ar.",
        no_corpo : "falta de ar, suor frio, tontura, náusea, sensação de desmaio.",
        sensorial : "dor intensa no peito, sensação de aperto ou pressão.",
        na_cognicao : "ansiedade extrema, sensação de morte iminente.",
        no_rosto : "pálido ou com suor excessivo.",
        intensidade : "Alta - A dor e os sintomas são geralmente graves e requerem atenção médica imediata.",
        duração : "Os sintomas podem durar vários minutos a horas e persistem até o tratamento ser administrado.",
        causas : "Obstrução de uma artéria coronária devido a um coágulo sanguíneo.",
        fatores_de_risco : "Hipertensão, colesterol alto, tabagismo, diabetes, obesidade, histórico familiar de doenças cardíacas, sedentarismo.",
        fatores_agravantes : "Estresse, hipertensão não controlada, dieta rica em gorduras saturadas, sedentarismo.",
        fatores_aliviantes : "Medicamentos específicos para dilatar as artérias e reduzir a dor, como nitroglicerina.",
        prevencao : "Manter uma dieta saudável, prática regular de exercícios, controle do colesterol e da pressão arterial, não fumar, gerenciar o estresse.",
        tratamento : "Administração de medicamentos anticoagulantes, trombolíticos, angioplastia ou cirurgia de revascularização miocárdica.",
        link_artigo : "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/i/infarto",
        link_video : "https://www.youtube.com/watch?v=sEY_kS4fb-g&pp=ygUHaW5mYXJ0bw%3D%3D",
        },

        { 
            titulo : "Asma Grave",
            descricao : "A asma grave é uma condição crônica que afeta as vias respiratórias, causando episódios recorrentes de falta de ar, chiado, aperto no peito e tosse. Em casos graves, pode ser potencialmente fatal se não for tratada rapidamente.",
            nivel_de_emergencia : "Emergência Moderada a Crítica",
            casos_por_ano : "Cerca de 1,3 Milhão de Casos",
            link_para_ligacao : "tel:+55192",
            nos_musculos : "tensão muscular no peito devido ao esforço para respirar.",
            na_visao : "possível visão turva devido à falta de oxigênio.",
            na_fala : "dificuldade para falar, podendo formar frases curtas devido à falta de ar.",
            no_corpo : "falta de ar intensa, chiado, sensação de aperto no peito, tosse persistente.",
            sensorial : "sensação de sufocamento, necessidade urgente de respirar.",
            na_cognicao : "confusão mental e ansiedade devido à dificuldade respiratória.",
            no_rosto : "pálido, lábios ou unhas podem ficar azulados (cianose) devido à falta de oxigênio.",
            intensidade : "Alta - Pode variar de moderada a grave, com potencial para evoluir rapidamente para uma emergência crítica.",
            duração : "Os episódios podem durar minutos a horas, dependendo da gravidade e do tratamento recebido.",
            causas : "Inflamação e estreitamento das vias aéreas devido a fatores desencadeantes como alérgenos, poluição, exercícios ou infecções respiratórias.",
            fatores_de_risco : "Histórico familiar de asma, alergias, exposição a fumaça de cigarro, poluição, obesidade, infecções respiratórias frequentes.",
            fatores_agravantes : "Exposição a alérgenos, infecções respiratórias, poluição, mudanças climáticas, estresse.",
            fatores_aliviantes : "Uso de broncodilatadores, corticosteróides inalados, evitar os fatores desencadeantes conhecidos.",
            prevencao : "Evitar alérgenos, tomar medicação prescrita regularmente, manter um ambiente livre de fumaça e poluição, prática de exercícios físicos moderados.",
            tratamento : "Administração de broncodilatadores de ação rápida, corticosteróides, oxigenoterapia em casos graves, e manejo contínuo com medicamentos preventivos.",
            link_artigo : "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/a/asma",
            link_video : "https://www.youtube.com/watch?v=sLXthX2fCFY&list=PLLcA2I5B3SEPGHPkhxTucHY7AGbWGsAH9&index=41&pp=iAQB",
            },

            { 
                titulo : "Hemorragias",
                descricao : "Hemorragia é a perda excessiva de sangue, que pode ocorrer de forma interna ou externa. Dependendo da gravidade e da localização, a hemorragia pode ser fatal se não for tratada imediatamente.",
                nivel_de_emergencia : "Emergência Crítica",
                casos_por_ano : "Milhares de Casos (variando por tipo e causa)",
                link_para_ligacao : "tel:+55192",
                nos_musculos : "fraqueza muscular devido à perda de sangue, cãibras.",
                na_visao : "visão turva, escurecimento da visão, desmaios.",
                na_fala : "dificuldade para falar devido à perda de consciência ou choque.",
                no_corpo : "pele pálida ou fria, suor excessivo, pulso fraco, tontura, queda de pressão arterial.",
                sensorial : "sensação de desmaio, formigamento nas extremidades.",
                na_cognicao : "confusão, desorientação, perda de consciência em casos graves.",
                no_rosto : "pálido, lábios azulados devido à falta de oxigênio (cianose).",
                intensidade : "Extremamente Variável - Pode ser leve e localizada ou grave e potencialmente fatal.",
                duração : "Pode durar minutos a horas, dependendo da fonte e do controle da hemorragia.",
                causas : "Trauma físico, lesões internas, doenças que afetam a coagulação do sangue, úlceras, aneurismas rompidos, complicações cirúrgicas.",
                fatores_de_risco : "Acidentes, cirurgia, distúrbios de coagulação, uso de anticoagulantes, hipertensão, alcoolismo.",
                fatores_agravantes : "Movimento ou esforço físico que aumenta a perda de sangue, falta de tratamento imediato.",
                fatores_aliviantes : "Aplicação de compressão direta para conter a hemorragia, elevação da parte afetada, tratamento médico urgente.",
                prevencao : "Uso de equipamentos de proteção em atividades de risco, tratamento adequado de condições médicas que afetam a coagulação, cuidados após cirurgias.",
                tratamento : "Depende da gravidade, mas pode incluir compressão direta, sutura, transfusão de sangue, cirurgia de emergência.",
                link_artigo : "https://www.samunoroestepr.com.br/materia/dicas/3-hemorragias-conheca-os-tipos-e-como-cuidar",
                link_video : "https://www.youtube.com/watch?v=M--710LxzcE&pp=ygUSaGVtb3JyYWdpYSBkcmF1emlv",
            },

            { 
                titulo : "Reações Alérgicas Graves (Anafilaxia)",
                descricao : "A anafilaxia é uma reação alérgica grave e potencialmente fatal que ocorre de forma rápida. Ela pode ser desencadeada por alimentos, picadas de insetos, medicamentos ou outros alérgenos. Sem tratamento imediato, pode levar à morte.",
                nivel_de_emergencia : "Emergência Crítica",
                casos_por_ano : "Centenas de Milhares de Casos Globalmente",
                link_para_ligacao : "tel:+55192",
                nos_musculos : "fraqueza, cãibras, dificuldade para respirar devido à constrição das vias aéreas.",
                na_visao : "visão embaçada, tontura, sensação de desmaio.",
                na_fala : "dificuldade para falar devido ao inchaço da garganta e língua.",
                no_corpo : "urticária, inchaço (especialmente no rosto, lábios, língua e garganta), dificuldade para respirar, queda de pressão arterial, choque.",
                sensorial : "formigamento nas extremidades, sensação de calor.",
                na_cognicao : "ansiedade, confusão, sensação de morte iminente.",
                no_rosto : "inchaço, lábios azulados, palidez.",
                intensidade : "Extremamente Grave - Pode ser fatal se não tratada imediatamente.",
                duração : "Os sintomas geralmente ocorrem dentro de minutos após a exposição ao alérgeno e podem piorar rapidamente.",
                causas : "Exposição a alérgenos como alimentos (amendoim, frutos do mar), picadas de insetos, medicamentos, látex, entre outros.",
                fatores_de_risco : "Histórico de alergias, histórico pessoal ou familiar de anafilaxia, asma, certas condições médicas.",
                fatores_agravantes : "Exposição repetida ao alérgeno, falta de tratamento imediato.",
                fatores_aliviantes : "Administração imediata de epinefrina (adrenalina), e cuidados médicos de emergência.",
                prevencao : "Evitar alérgenos conhecidos, portar autoinjetor de epinefrina, uso de pulseira de alerta médico.",
                tratamento : "Administração de epinefrina, chamada para emergência médica, monitoramento e cuidados intensivos.",
                link_artigo : "https://www.rededorsaoluiz.com.br/doencas/anafilaxia",
                link_video : "https://www.youtube.com/watch?v=5znsktdP30s&pp=ygUpYW5hZmlsYXhpYSBlIGNob3F1ZSBhbmFmaWzDoXRpY28gIGRyYXV6aW8%3D",
            }     
]
